### ISSUE TITLE
Allow listening for multiple hostnames

### ISSUE THREAD

**Issue by damaliboyd** [fkmclane/carillon#2]

**Comment by lilyinstarlight** [comment]
That's probably going to require a way to make multiple of the block at
https://github.com/fkmclane/carillon/blob/82e4e92c45cb86699fd231ca5cd41e268bc7fba5/conf/Caddyfile.in#L31-L42
which is generated from
https://github.com/fkmclane/carillon/blob/82e4e92c45cb86699fd231ca5cd41e268bc7fba5/carillon#L203-L242

If Caddy lets you specify multiple hostnames in one line that would be much easier but you'll have to check their docs if there is a way to do that. This is still using Caddy v1.
